### ISSUE TITLE
Support captive portal redirection

### ISSUE THREAD

**Issue by hkolbeck** [ZanzyTHEbar/EasyNetworkManager#10]
You might already do this, but I didn't see it in the code. I haven't even started coding for the project I'm looking to use this with, but captive portal support would be amazing if it's not in place yet. Apologies if I just missed it.

**Is your feature request related to a problem? Please describe.**
Especially with embedded wifi usage where there's tiny or nonexistent screen UI, having folks redirected to the setup page would be amazing for when things aren't set up yet.

**Describe the solution you'd like**
I'd like the ability to add a redirection rule for all HTTP traffic when the service is in AP mode, sending folks to the existing setup page via inserted 302

**Describe alternatives you've considered**
Making sure folks know the default, workable but not user-friendly for non-technical folks.

**Comment by ZanzyTHEbar** [comment]
Hello, thank you for checking out my library 👍 

So, I have not yet implemented a proper captive portal. I have left that to the user, as this lib is already pretty bloated. Though, i can implement a captive portal behind a feature flag if you would like. 

That being said. the library supports a wifi manager to manage your mdns, wifi, and ota settings. This is locked behind a feature build flag. The wifimanager itself can be on any endpoint that you want, totally customizable using the `APIServer` class constructor, see the `main.cpp` example. You can also supply your own custom html files for anything that you want on their own endpoints and then use custom commands, using the `addAPICommand()` method, to interact with any custom Javascript. 

You could very easily build your own captive portal using the above mentioned features :) 

I am actively working on a thorough documentation website for this library, I apologize that it is not done yet. 

If you have any questions, feel free to ask them, i am happy to help and add clarity where needed,

**Comment by hkolbeck** [comment]
Exceptional! Thanks so much.

**Comment by ZanzyTHEbar** [comment]
No problem :) I will be simplifying the config API in a few days, make it more user friendly. As such, I will update the examples. 

Let me know if you have any questions, I am happy to help. I am actively working on a documentation website - hopefully that will be done soon.
